server:
  address:     ":8801"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  graceful: true              # 是否开启平滑重启特性，开启时将会在本地增加10000的本地TCP端口用于进程间通信。默认false

logger:
  level : "all"
  stdout: true
# 关系型数据库
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: ["RequestId"]
  default: #默认数据库
    type: "sqlite" # mysql,sqlite
    debug: true
    charset: "utf8mb4"
    maxIdle: "0"       #连接池最大闲置的连接数
    maxOpen: "10"      #连接池最大打开的连接数
    maxLifetime: "30s"  #连接对象可重复使用的时间长度
    # link: "mysql:root:123456@tcp(localhost:3306)/RuoYi-Go-Plus?loc=Local&parseTime=true"
    link: "sqlite::@file(./resource/db/ruoyi-go-plus.db)" #数据库路径根据自己的填写
# 文件上传设置
upload:
  path: "upload"
